<?php

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group([
        'key' => 'grupo_campos_pet',
        'title' => 'Pets',
        'fields' => [
            [
                'key' => 'pet_nome',
                'label' => 'Nome do Pet',
                'name' => 'pet_nome',
                'type' => 'text',
                'prefix' => '',
                'instructions' => 'O nome do pet',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],
            [
                'key' => 'pet_raca',
                'label' => 'Raça do Pet',
                'name' => 'pet_raca',
                'type' => 'text',
                'prefix' => '',
                'instructions' => 'A raça a qual o pet pertence',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],
            [
                'key' => 'pet_cor_pelo',
                'label' => 'Cor do Pelo',
                'name' => 'pet_cor_pelo',
                'type' => 'text',
                'prefix' => '',
                'instructions' => 'A coloração do pelo do pet',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],
            [
                'key' => 'pet_tamanho',
                'label' => 'Tamanho',
                'name' => 'pet_tamanho',
                'type' => 'select',
                'prefix' => '',
                'instructions' => 'O porte ou tamanho do pet',
                'choices' => [
                    'mini' => 'Mini',
                    'pequeno' => 'Pequeno',
                    'medio' => 'Médio',
                    'grande' => 'Grande',
                    'gigante' => 'Gigante',
                ],
                'allow_null' => 0,
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],
            [
                'key' => 'pet_imagem',
                'label' => 'Imagem Destacada',
                'name' => 'pet_imagem',
                'type' => 'image',
                'prefix' => '',
                'instructions' => 'Uma imagem representativa do pet',
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ],

        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'pets',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ]);

endif;
